# Change these first
owner: dsmgid # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: DSMG Home
    url: https://dsgroupmedia.com
  - name: DSMG Cloud Home
    url: https://dsmg.cloud
  - name: DSMG Cloud Premium Panel
    url: https://member.dsmg.cloud
  - name: DSMG Cloud Free Panel
    url: https://member.dsmg.my.id
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dsmg.my.id
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://static.dsgroupmedia.com/logo/dsmg-cloud.png
  name: Upptime
  introTitle: "DSMG Cloud Status Page"
  introMessage: All the service status will be shown here
  navbar:
    - title: Status
      href: /
    - title: Free Hosting Client Area
      href: https://member.dsmg.my.id
    - title: Premium Hosting Client Area
      href: https://member.dsmg.cloud

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
